[package]
name = "mahjong"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "mahjong"
crate-type = ["cdylib"]

[dependencies]
cargo-llvm-cov = "0.6.14"
pyo3 = "0.23.0"
rand = "0.8"
