[package]
name = "mahjong"
version = "0.1.0"
edition = "2021"

[lib]
name = "mahjong"
crate-type = ["cdylib", "rlib"]

[dependencies]
pyo3 = "0.25.0"
rand = "0.8"

[dev-dependencies]
criterion = { version = "0.5", features = ["html_reports"] }

[[bench]]
name = "mahjong_benchmark"
harness = false
